New branch
javitolez/Hello-Microverse pull request #1
Opened 2022-05-24 23:56 UTC by javitolez

Hello Microverse.

Configurate and practice of Github.

commit .gitignore
commit style.css
commit index.html

2022-05-25 01:00 UTC, rloterh requested changes
Hi Javier, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦 🚦 🚦  

## Highlights 👍  
- Meaningful commit messages
- Sample files correctly pushed to the repository
- Correct gitflow used


## Required Changes ♻️
_Kindly check the comments below and under the review:_

Linters are not passing. I follow the steps listed [here](https://github.com/microverseinc/linters-config/tree/master/html-css) and ensure that the required linters are properly installed and passing accordingly:
- [x] Linter should be set up correctly for this repository.
- [ ] Linter result should be green. AKA: Linter should report NO errors.
- [ ] There should be no custom changes to linter config (as an attempt to cheat linter error reports).

Your Pull Request title and description should be more descriptive. Kindly follow this [guidelines](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) to ensure that your PR looks more professional. Kindly ensure that:
- [ ] Pull Request should have a descriptive title telling you what changes are inside.
- [ ] Pull Request should have a summary describing introduced changes in more detail.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Kindly check the comments marked **[OPTIONAL]** under the review._

<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-25 01:00 UTC, rloterh commented on .gitignore
> +test.md
- [ ] Kindly ensure to include the `node_modules` directory in the _.gitignore_ file so the _node packages_ during linter installation would not be included during the _commit_ of the repository

2022-05-25 01:00 UTC, rloterh commented on README.md
> +## Authors
- [ ] OPTIONAL
Kindly change the header title _Authors_ to _Author_, as this project is done solely. This will make your ReadMe appear more professional.

2022-05-25 01:00 UTC, rloterh commented on README.md
> +👤 **Author1** Javier Lezama
- [ ] OPTIONAL
Kindly replace the text **Author1** with your full name, so as to make your ReadMe more professional

2022-05-25 01:00 UTC, rloterh commented on README.md
> +[Live Demo Link](https://localhost)
- [ ] Kindly remove demo link which is not working

2022-05-25 01:00 UTC, rloterh commented on README.md
> +### Deployment
- [ ] Kindly ensure to add the necessary steps required to setup your project

2022-05-27 13:43 UTC, Lucas-Masaba requested changes
# Hello @javitolez  👋 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.


## Invalid Code Review Request ⚠️ 

You have submitted a project, that does not have linter checks passing. Please make sure all your linter cheks have a checkmark ✔️  and not an ❌ as seen below
![image](https://user-images.githubusercontent.com/45460192/170711307-9e9aa258-7bce-4bb1-a770-e0726cbc6cd5.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-28 21:27 UTC, DeliceLydia approved these changes
## Hi @javitolez, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 21:38 UTC, merged